spring.application.name=stock-trading-engine

# SERVER PORT
server.port=8080

# MYSQL DATABASE CONNECTION
spring.datasource.url=jdbc:mysql://localhost:3306/trading_engine

spring.datasource.username=root
spring.datasource.password=ROOT

# JPA SETTINGS
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MYSQL DIALECT
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect